/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_igrok_net_engine_ui_NativeWindow */

#ifndef _Included_org_igrok_net_engine_ui_NativeWindow
#define _Included_org_igrok_net_engine_ui_NativeWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_igrok_net_engine_ui_NativeWindow
 * Method:    createWindow
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_ui_NativeWindow_createWindow
  (JNIEnv *, jclass, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
