/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_igrok_net_engine_ui_IGNWindow */

#ifndef _Included_org_igrok_net_engine_ui_IGNWindow
#define _Included_org_igrok_net_engine_ui_IGNWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_igrok_net_engine_ui_IGNWindow
 * Method:    CreateNativeWindow
 * Signature: (Ljava/lang/String;IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_ui_IGNWindow_CreateNativeWindow
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     org_igrok_net_engine_ui_IGNWindow
 * Method:    DestroyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_engine_ui_IGNWindow_DestroyWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_igrok_net_engine_ui_IGNWindow
 * Method:    MainLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_engine_ui_IGNWindow_MainLoop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
