/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_igrok_net_ignfreeglut_IGNFreeGlut */

#ifndef _Included_org_igrok_net_ignfreeglut_IGNFreeGlut
#define _Included_org_igrok_net_ignfreeglut_IGNFreeGlut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_igrok_net_ignfreeglut_IGNFreeGlut
 * Method:    glutInit
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_ignfreeglut_IGNFreeGlut_glutInit
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
