/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_igrok_net_ignfreeglut_IGNFreeGlut */

#ifndef _Included_org_igrok_net_ignfreeglut_IGNFreeGlut
#define _Included_org_igrok_net_ignfreeglut_IGNFreeGlut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_igrok_net_ignfreeglut_IGNFreeGlut
 * Method:    glutInitNative
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_ignfreeglut_IGNFreeGlut_glutInitNative
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_igrok_net_ignfreeglut_IGNFreeGlut
 * Method:    glutInitWindowPositionNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_ignfreeglut_IGNFreeGlut_glutInitWindowPositionNative
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_igrok_net_ignfreeglut_IGNFreeGlut
 * Method:    glutInitWindowSizeNative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_ignfreeglut_IGNFreeGlut_glutInitWindowSizeNative
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
