/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_igrok_net_engine_IGNEngine */

#ifndef _Included_org_igrok_net_engine_IGNEngine
#define _Included_org_igrok_net_engine_IGNEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    init
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_engine_IGNEngine_init
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    printString2D
 * Signature: (IIFFFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_engine_IGNEngine_printString2D
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jstring);

#ifdef __cplusplus
}
#endif
#endif
