/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_igrok_net_engine_IGNEngine */

#ifndef _Included_org_igrok_net_engine_IGNEngine
#define _Included_org_igrok_net_engine_IGNEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    GLUT_STROKE_ROMAN
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_IGNEngine_GLUT_1STROKE_1ROMAN
  (JNIEnv *, jclass);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    GLUT_STROKE_MONO_ROMAN
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_IGNEngine_GLUT_1STROKE_1MONO_1ROMAN
  (JNIEnv *, jclass);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    GLUT_BITMAP_9_BY_15
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_IGNEngine_GLUT_1BITMAP_19_1BY_115
  (JNIEnv *, jclass);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    GLUT_BITMAP_8_BY_13
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_IGNEngine_GLUT_1BITMAP_18_1BY_113
  (JNIEnv *, jclass);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    GLUT_BITMAP_TIMES_ROMAN_10
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_IGNEngine_GLUT_1BITMAP_1TIMES_1ROMAN_110
  (JNIEnv *, jclass);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    GLUT_BITMAP_TIMES_ROMAN_24
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_IGNEngine_GLUT_1BITMAP_1TIMES_1ROMAN_124
  (JNIEnv *, jclass);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    GLUT_BITMAP_HELVETICA_10
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_IGNEngine_GLUT_1BITMAP_1HELVETICA_110
  (JNIEnv *, jclass);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    GLUT_BITMAP_HELVETICA_12
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_IGNEngine_GLUT_1BITMAP_1HELVETICA_112
  (JNIEnv *, jclass);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    GLUT_BITMAP_HELVETICA_18
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_igrok_1net_engine_IGNEngine_GLUT_1BITMAP_1HELVETICA_118
  (JNIEnv *, jclass);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    init
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_engine_IGNEngine_init
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    printString2D
 * Signature: (IIFFFFLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_engine_IGNEngine_printString2D
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat, jstring, jlong);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    MeasureString
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_igrok_1net_engine_IGNEngine_MeasureString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_igrok_net_engine_IGNEngine
 * Method:    RenderQuad
 * Signature: (IIIIFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_org_igrok_1net_engine_IGNEngine_RenderQuad
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
